### ISSUE TITLE
Convert WebEx to Youtube

### ISSUE THREAD

**Issue by radhikabhatt26** [CommerceDataService/Commerce_Data_Academy_Courses#12]
As a CDA organizer, I can take the webex recordings and convert them to youtube videos.
## Definition of Done
- [x] Determine if CDA/CDS/Commerce has a Youtube channel
- [ ] Get CDA youtube videos approved
- [x] Research webex to youtube conversion
## Acceptance Criteria
- [ ] Webex can be converted to youtube videos
- [ ] We can put youtube videos on CDA site

**Comment by arowla** [comment]
Blocked by CommerceDataService/DataAcademy#10

**Comment by arowla** [comment]
The Commerce Youtube channel is what we'll use.
