### ISSUE TITLE
WebEx/Previous Recordings Page

### ISSUE THREAD

**Issue by radhikabhatt26** [CommerceDataService/Commerce_Data_Academy_Courses#6]
As a user, I want to access previous recordings of classes I could not attend in person, or classes I would like to revisit.
## Definition of Done
- [ ] Compile list of webex/youtube recordings 
- [ ] Front end code written
## Acceptance Criteria
- [ ] All previous classes webex/youtube links are available and live

**Comment by arowla** [comment]
Blocked by CommerceDataService/DataAcademy#10

**Comment by arowla** [comment]
Let's come back and scope this Issue down to adding a few specific classes, once they are transcribed.
